ministryofJusticeApp/ministryofjusticeWebUi/Models/AssignCaseViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using ministryofjusticeDomain.Entities;
using ministryofjusticeDomain.IdentityEntities;

namespace ministryofjusticeWebUi.Models
{
    public class AssignCaseViewModel
    {
        [Required]
        public int CaseId { get; set; }
        public Case Case { get; set; }
        public IEnumerable<Lawyer> Lawyers { get; set; }
        [Display(Name = "Lawyer")]
        public int LawyerId { get; set; }

        public Lawyer Lawyer { get; set; }
        public IEnumerable<ApplicationUser> Users { get; set; }
    }
}

ministryofJusticeApp/ministryofjusticeWebUi/Models/CaseDetailsViewModel.cs
using ministryofjusticeDomain.Entities;
using ministryofjusticeDomain.Enum;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ministryofjusticeWebUi.Models
{
    public class CaseDetailsViewModel
    {

        public int Id { get; set; }
        public string CaseID { get; set; }
        public string Fullname { get; set; }
        public string Email { get; set; }
        public string ReportSubject { get; set; }
        public string AdditionalInformation { get; set; }
        public string PhoneNumber { get; set; }
        public Gender GenderID { get; set; }
        public Status StatusID { get; set; }
        public DateTime SubmitDate { get; set; }
        public ICollection<Comment> Comments { get; set; } 
        public int DepartmentId { get; set; }
        public IEnumerable<Department> Departments { get; set; }
        public IEnumerable<Lawyer> Lawyers { get; set; }
        public Department Department { get; set; }

        public CommentViewModel Comment { get; set; } 
        public Lawyer Lawyer { get; set; }
        public int? LawyerId { get; set; }
        //  public ICollection<Lawyer> Lawyers { get; set; }
        public File File { get; set; }
        public Pagination Pagination { get; set; }

        public bool IsAccepted()
        {
            if (StatusID == Status.Accepted || StatusID == Status.Assigned
            || StatusID == Status.Processing || StatusID == Status.RequestClose) 
                return true;
            return false;
        }

        public string GetBadgeColor()
        {
            switch (StatusID)
            {
                case Status.Pending:
                    return "primary";
                case Status.Assigned:
                    return "success"; 
                case Status.Accepted:
                    return "secondary";
                case Status.Rejected:
                    return "danger";
                case Status.Closed:
                    return "black";
                case Status.RequestClose:
                    return "dark";
                default:
                    return "yellow";
            }
        }
        public string GetTextColor()
        {
            switch (StatusID)
            {
                case Status.Pending:
                    return "primary";
                case Status.Assigned:
                    return "success";
                case Status.Accepted:
                    return "secondary";
                case Status.Rejected:
                    return "danger";
                case Status.Closed:
                    return "black";
                case Status.RequestClose:
                    return "dark";
                default:
                    return "yellow";
            }
        }
    }
}

ministryofJusticeApp/ministryofjusticeWebUi/Models/CaseViewModel.cs
using ministryofjusticeDomain.Entities;
using ministryofjusticeDomain.Enum;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ministryofjusticeWebUi.Models
{
    public class CaseViewModel
    {
        //public int? Id { get; set; }
        public string CaseID { get; set; }
        [Required(ErrorMessage = "You have to enter your full name")]
        [Display(Name = "Full Name")]
        public string Fullname { get; set; }
        [Required(ErrorMessage = "You have to enter your email address")]
        [Display(Name = "Email Address")]
        public string Email { get; set; }
        [Required(ErrorMessage = "You have to enter a heading for this report")]
        [Display(Name = "Report Title")]
        public string ReportSubject { get; set; }
        [Required(ErrorMessage = "Add Report Details")]
        [DisplayName("Details of Report")]
        [DataType(DataType.MultilineText)]
        public string AdditionalInformation { get; set; }
        [Required(ErrorMessage = "You have to enter your phone number")]
        [Display(Name = "Phone Number")]
        [DataType(DataType.PhoneNumber)]
        public string PhoneNumber { get; set; }
        [Range(1, int.MaxValue, ErrorMessage = "Selelct Gender")]
        [Display(Name="Gender")]
        public Gender GenderID { get; set; }
        public Status StatusID { get; set; }
        public DateTime SubmitDate { get; set; }
        [Required(ErrorMessage = "You have to choose a report type")]
        [Display(Name = "Report Type")]
        public int DepartmentId { get; set; }
        public IEnumerable<Department> Departments { get; set; }

    }
}

ministryofJusticeApp/ministryofjusticeWebUi/Controllers/CaseController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using ministryofjusticeDomain.Entities;
using ministryofjusticeDomain.Enum;
using ministryofjusticeDomain.Interfaces.Repository;
using ministryofjusticeWebUi.Interfaces;
using ministryofjusticeWebUi.Models;

namespace ministryofjusticeWebUi.Controllers
{
	[Authorize]
	public class CaseController : Controller
	{
		private readonly ICaseService _caseService;

		public CaseController()
		{
		}

		public CaseController(ICaseService caseService)
		{
			_caseService = caseService;
		}

        private int pageSize = 5;

		// GET: Case
		public ActionResult Index(string status = null, int page = 1)
        {
            var cases = _caseService.GetCases(QueryType.Status, status);
            var casesList = new CaseListViewModel()
            {
				Cases = cases
				    .OrderByDescending(_ => _.Id)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize),
				PageInfo = new Pagination()
                {
					CurrentPage = page,
					ItemsPerPage = pageSize,
					TotalItems = cases.Count()
                }
            };
			ViewBag.Title = (status ?? "All") + " Cases";
			return View(casesList);
		}

		/// <summary>
		/// Returns a table of cases assigned to a department
		/// </summary>
		/// <param name="assigned">Either "Assigned" or "Unassigned"</param>
		/// <returns>List of cases based on the case details view model</returns>
		public ActionResult DepartmentCases(string assigned = null, int page = 1)
		{
			var cases = _caseService.GetCases(QueryType.Assigned, assigned);
            var casesList = new CaseListViewModel()
            {
                Cases = cases
				    .OrderByDescending(_ => _.Id)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize),
                PageInfo = new Pagination()
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = cases.Count()
                }
            };
			ViewBag.Title = (assigned ?? "All") + " Department cases";
			return View("Index", casesList);
		}

		/// <summary>
		/// Returns a detail view of the case
		/// </summary>
		/// <param name="id">the ID of the case</param>
		/// <returns></returns>
		public ActionResult CaseDetails(int id)
		{
			var vm = _caseService.GetCaseDetails(id);
			if (vm == null)
				return HttpNotFound("Case not found");
			return View(vm);
		}

		public ActionResult AssignedCases(int page = 1)
		{
			var lCases = _caseService.GetCases(QueryType.LawyerCase);
            var casesList = new CaseListViewModel()
            {
                Cases = lCases
				        .OrderByDescending(_ => _.Id)
                        .Skip((page - 1) * pageSize)
                        .Take(pageSize),
                PageInfo = new Pagination()
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = lCases.Count()
                }
            }; 
			return View("Index", casesList);
		}

		public ActionResult LawyerViewCase(int id)
		{
			var caseDetail = _caseService.GetCaseDetails(id);
			return View("CaseDetails", caseDetail);
		}

		public PartialViewResult ShowLawyers(int id)
		{
			var vm = _caseService.GetCaseLawyers(id);
			return PartialView("_AssignLawyer", vm);
		}

		public ActionResult AssignLawyer(int id, int lawyerId)
		{
			var boolean = _caseService.AssignAction(id, lawyerId, CaseAction.Assign);
			if (!boolean) return HttpNotFound("Case was not assigned");
			TempData["Message"] = $"Case has been assign";
			return RedirectToAction("DepartmentCases");
		}


		public ActionResult UnAssignLawyer(int id, int lawyerId)
		{
			var caseUnassigned = _caseService.AssignAction(id, lawyerId, CaseAction.UnAssign);

			if (!caseUnassigned) return HttpNotFound("case was not assigned");

			TempData["Message"] = $"Lawyer has been unassigned from the case";
			return RedirectToAction("DepartmentCases");
		}

		/// <summary>
		/// Called when the attorney general accepts a case
		/// </summary>
		/// <param name="id">The id of the case</param>
		/// <returns>The case details with case status of assigned</returns>
		public ActionResult AssignToDepartment(int id)
		{
			_caseService.AuditCase(id, CaseAction.Accept);
			var vm = _caseService.GetCaseDetails(id);
			TempData["Message"] = $"Case has been assigned to {vm.Department.DepartmentName} Department";

			//Notify user that this case has been accepted
			_caseService.NotifyClient(vm);
			return View("CaseDetails", vm);
		}

		/// <summary>
		/// Called when the attorney general rejects a case
		/// </summary>
		/// <param name="id"></param>
		/// <returns>The case details with case status of rejected</returns>
		public ActionResult RejectCase(int id)
		{
			_caseService.AuditCase(id, CaseAction.Reject);
			var vm = _caseService.GetCaseDetails(id);
			TempData["Message"] = $"Case has been rejected";

			//Notify user that this case has been rejected
			_caseService.NotifyClient(vm);
			return View("CaseDetails", vm);
		}

		public PartialViewResult SearchForm()
		{
			var vm = new SearchCasesViewModel();
			return PartialView("_SearchCase", vm);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult SearchResult(SearchCasesViewModel model)
		{
			var category = model.Category;
			var query = model.SearchValue;
			return RedirectToAction("Search", new { category = category, query = query });
		}

		/// <summary>
		/// Returns search results for cases based on category and the query value
		/// </summary>
		/// <param name="category">Either case ID or client email</param>
		/// <param name="query">Query parameter</param>
		/// <returns></returns>
		public ActionResult Search(string category, string query)
		{
			var queryParam = $"category={category}&param={query}";
			var vm = _caseService.GetCases(QueryType.Search, queryParam);
			ViewBag.searchValue = query;
			ViewBag.searchParameter = category.ToLower();
			return View(vm);
		}

		public PartialViewResult GetComment(int caseId)
		{

			var vm = new CommentViewModel();

			return PartialView("_CaseComments");
		}


		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult SaveComment(CaseDetailsViewModel model)
		{
			if (!ModelState.IsValid)
				return RedirectToAction("CaseDetails");

			var comment = Mapper.Map<CommentViewModel, Comment>(model.Comment);
			comment.CreatedAt = DateTime.Now;
			_caseService.InsertComment(comment);
			model.Id = comment.Id;
			return PartialView("_CaseComments");
		}
		public ActionResult ProcessingCase(int id, Status status)
		{
			var boolean = _caseService.CaseStatusChange(id, status);
			if (!boolean) return HttpNotFound("Case was not assigned");
			var caseDetail = _caseService.GetCaseDetails(id);

			if (status == Status.Processing)
			{
				TempData["Message"] = $"You are currently processing this case";
				return RedirectToAction("CaseDetails", caseDetail);
			}
			if (status == Status.RequestClose)
			{
				TempData["Message"] = $"You request has been sent";
				return RedirectToAction("CaseDetails", caseDetail);
			}
			if (status == Status.Closed)
			{
				TempData["Message"] = $"You have closed case: {caseDetail.CaseID}";
				return RedirectToAction("RequestClose");
			}
			return RedirectToAction("CaseDetails", caseDetail);
		}

		public ActionResult RequestClose()
		{
			var cases = _caseService.GetCases(QueryType.Status, "Request to Close");

			return View(cases);

		}
	}
}

ministryofJusticeApp/ministryofjusticeWebUi/Controllers/FileController.cs
using System.Web;
using System.Web.Mvc;
using ministryofjusticeWebUi.Interfaces;
using ministryofjusticeWebUi.Models;

namespace ministryofjusticeWebUi.Controllers
{
	[Authorize]

	public class FileController : Controller
	{
		private readonly ICaseFileServices _caseFileServices;
		public FileController()
		{

		}

		public FileController(ICaseFileServices caseFiles)
		{
			_caseFileServices = caseFiles;
		}

		public ActionResult ManageCaseFiles(int id)
		{
			var viewModel = _caseFileServices.ManageCaseFiles(id);
			return View(viewModel);
		}

		//[HttpGet]
		public ActionResult UploadCaseFile(int id)
		{
			var uploadFileView = new UploadFileViewModels()
			{
				CaseId = id
			};
			return View(uploadFileView);
		}

		[HttpPost]
		public ActionResult UploadCaseFile(UploadFileViewModels uploadFile, HttpPostedFileBase file)
		
		{
			if (ModelState.IsValid)
			{
				if (file != null)
				{
					var path = Server.MapPath("~/CaseFiles/");
					var result = _caseFileServices.UploadCaseFile(uploadFile, path, file);
					if (result)
					{
						TempData["Message"] = "File Successfully Uploaded";
						return RedirectToAction("ManageCaseFiles", new { id = uploadFile.CaseId });
					}
				}

				ModelState.Clear();
			}
			return View();
		}

		// GET: File
		public ActionResult DeleteFile(int id, int caseId)
		{
			var result = _caseFileServices.DeleteFile(id);
			return RedirectToAction("ManageCaseFiles", new { id = caseId });
		}
		 public ActionResult FileNotFound(string returnUrl)
		{
			//So that the user can be referred back to where they were when they click ViewFile
			if (string.IsNullOrEmpty(returnUrl) && Request.UrlReferrer != null)
				returnUrl = Server.UrlEncode(Request.UrlReferrer.PathAndQuery);

			if (Url.IsLocalUrl(returnUrl) && !string.IsNullOrEmpty(returnUrl))
			{
				ViewBag.ReturnURL = returnUrl;
			}
			return View();
		}
		/// <summary>
		/// this loads a file in  a new tab
		/// </summary>
		/// <param name="path"></param>
		/// <returns></returns>
		/// 
		public ActionResult Download(string path)
		{
			string type = _caseFileServices.GetFileType(path);
			if (type.Equals("Not Found"))
				return View("FileNotFound");
			if (type.Equals("pdf"))
			{
				byte[] FileBytes = System.IO.File.ReadAllBytes(path);
				return this.File(FileBytes, "application/pdf");
			}
			var file = this.File(path, type);
			return file;
		}

	}
}

ministryofJusticeApp/ministryofjusticeWebUi/Views/Case/AssignCase.cshtml
@using ministryofjusticeWebUi.Models
@model AssignCaseViewModel

@{
    ViewBag.Title = "AssignCase";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
    var vm = Model;
}

<header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
    <div class="container-fluid">
        <div class="page-header-content">
            <div class="row align-items-center justify-content-between pt-3">
                <div class="col-auto mb-3">
                    <h1 class="page-header-title">
                        <div class="page-header-icon">
                            <i data-feather="user"></i>
                        </div>
                        Assign Lawyers - @ViewBag.Title
                    </h1>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container mt-4">
    <article class="card mb-4">
        <header class="card-header d-flex align-items-center">
            <a class="btn btn-transparent-dark btn-icon" href="@Url.Action("DepartmentCases")">
                <i data-feather="arrow-left"></i>
            </a>
            <div class="ml-3">

                @if (vm.Case.Lawyer == null)
                {
                    <h2 class="my-3">
                        Assign lawyer to case:#@vm.Case.CaseID
                    </h2>
                }

            </div>
        </header>
        <div class="card-body">
            @if (vm.Lawyers.Any())
            {
                <div class="mr-3 ">

                    @foreach (var lawyer in vm.Lawyers)
                    {
                        <div class="d-flex justify-content-between align-items-center">

                            <div>
                                <h3>@lawyer.User.FullName</h3>
                                @if (lawyer.AssignedCases != null)
                                {
                                    <p>@lawyer.AssignedCases.Count()</p>
                                }
                                else
                                {
                                    <p>no case</p>
                                }
                            </div>


                            <div class="mb-3">
                                @if (lawyer.AssignedCases != vm.Case)
                                {
                                    <a class="btn btn-success mx-2 px-3" role="button"
                                       href="@Url.Action("AssignLawyer", "Case", new {id = vm.CaseId, lawyerId = lawyer.Id})">
                                        <i class="mr-2" data-feather="check-square"></i>
                                        Assign
                                    </a>
                                }
                                else if (vm.Case.LawyerId == lawyer.Id)
                                {
                                    <a class="btn btn-success mx-2 px-3" role="button"
                                       href="@Url.Action("UnAssignLawyer", "Case", new {id = vm.CaseId, lawyerId = lawyer.Id})">
                                        <i class="mr-2" data-feather="check-square"></i>
                                        UnAssign
                                    </a>
                                }

                            </div>

                        </div>
                    }
                </div>
            }
            else
            {
                <div class="py-4 text-center">
                    <h2 class="text-primary-soft">No lawyers available!</h2>
                    <p class="text-muted font-italic">There are no lawyers in this department yet</p>
                </div>
            }
        </div>
    </article>
</div>

ministryofJusticeApp/ministryofjusticeWebUi/Views/Case/CaseDetails.cshtml
@using ministryofjusticeDomain.Enum
@using ministryofjusticeWebUi.Models
@model CaseDetailsViewModel
@{
    Layout = "~/Views/Case/_CaseLayout.cshtml";
    var caseDetail = Model;
    ViewBag.Title = $"Details of {caseDetail.CaseID}";
}


<!-- Knowledge base article-->
<article class="card mb-4">
    <header class="card-header d-flex align-items-baseline justify-content-between">
        <div class="d-flex align-items-center">
            @if (User.IsInRole("Attorney General"))
            {
                <a class="btn btn-transparent-dark btn-icon" href="@Url.Action("Index")">
                    <i data-feather="arrow-left"></i>
                </a>
            }
            else if (User.IsInRole("Director of Department"))
            {
                <a class="btn btn-transparent-dark btn-icon" href="@Url.Action("DepartmentCases")">
                    <i data-feather="arrow-left"></i>
                </a>
            }
            else if (User.IsInRole("Lawyer"))
            {
                <a class="btn btn-transparent-dark btn-icon" href="@Url.Action("AssignedCases")">
                    <i data-feather="arrow-left"></i>
                </a>
            }
            <div class="ml-3">
                <h2 class="mb-1">Subject: @caseDetail.ReportSubject</h2>
                <h4 class="my-3">@caseDetail.CaseID</h4>
                <div class="badge badge-md badge-@caseDetail.GetBadgeColor()">@caseDetail.StatusID</div>
            </div>
        </div>

        <div class="text-md-right">
            @if (!User.IsInRole("Director of Department"))
            {
                <a class="my-3 link list-inline ml-lg-10"
                   href="@Url.Action("ManageCaseFiles", "File", new {id = caseDetail.Id})"> View Case Files</a>
            }
            @if(User.IsInRole("Director of Department") || User.IsInRole("Attorney General"))
            {
                if (caseDetail.LawyerId != null)
                {
                    <p class="text-black-75">Assigned Lawyer: @caseDetail.Lawyer.User.FullName</p>
                }
            }
        </div>
    </header>
    <div class="card-body">
        <div class="py-2 d-flex justify-content-between w-100 px-2">
            <div class="person-detail">
                <h4 class="text-black-50">Submitted by @caseDetail.Fullname</h4>
                <p class="small mb-1">
                    <span class="mr-3">Email: @caseDetail.Email</span>
                </p>
                <p class="m-0 small">Sex: @caseDetail.GenderID</p>
            </div>
            <div id="time-details">
                <h4 class="text-black-50">Time Submitted</h4>
                <p>@caseDetail.SubmitDate</p>
            </div>


        </div>
        <hr class="mt-2 mb-5" />
        <div class="px-md-4">
            <h4>Case details:</h4>
            <p class="lead">@caseDetail.AdditionalInformation</p>
        </div>
        <hr class="my-3" />
        @*<h4 class="mb-4">Evidence documents:</h4>
        <div class="row">
            <div class="col-sm-6 col-md-3">
                <div class="card shadow rounded w-100">
                    <div class="card-header text-black-50">
                        <i data-feather="file"></i>File 1
                    </div>
                    <div class="card-body text-center">
                        <h2 class="text-gray-500 my-3">
                            <i data-feather="file" class="text-black-50"></i>
                        </h2>
                        <a href="#file-path">View file</a>
                    </div>
                </div>
            </div>
        </div>*@
    </div>
</article>
@{
    @Html.Partial("_CaseComments", Model)
}



<!-- Knowledge base rating-->
@Html.Partial("_CaseActions", caseDetail)

@if (User.IsInRole("Director of Department"))
{
    Html.RenderAction("ShowLawyers", new{ id=caseDetail.Id });
}

ministryofJusticeApp/ministryofjusticeWebUi/Views/Case/Index.cshtml
@using ministryofjusticeWebUi.Infrastructures
@using ministryofjusticeWebUi.Models
@model CaseListViewModel

@{
    Layout = "_CaseLayout.cshtml";
    var Cases = Model.Cases;
    var PageInfo = Model.PageInfo;
}

<!-- Cases page navigation-->
<nav class="nav nav-borders">
    @if (User.IsInRole("Attorney General"))
    {
        @Html.ActionLink("All Cases", "Index", null, new { @class = "nav-link ml-0" })
        @Html.ActionLink("Pending Cases", "Index", new { status = "Pending" }, new { @class = "nav-link" })
        @Html.ActionLink("Accepted Cases", "Index", new { status = "Accepted" }, new { @class = "nav-link" })
        @Html.ActionLink("Rejected Cases", "Index", new { status = "Rejected" }, new { @class = "nav-link" })
        @Html.ActionLink("Closed Cases", "Index", "Case", new { status = "Closed" }, new { @class = "nav-link" })

    }

    @if (User.IsInRole("Director of Department"))
    {
        @Html.ActionLink("Department Cases", "DepartmentCases", null, new { @class = "nav-link ml-0" })
        @Html.ActionLink("Assigned Cases", "DepartmentCases", new { assigned = "Assigned" }, new { @class = "nav-link" })
        @Html.ActionLink("Unassigned Cases", "DepartmentCases", new { assigned = "Unassigned" }, new { @class = "nav-link" })
    }

    @if (User.IsInRole("Lawyer"))
    {
        @Html.ActionLink("Assigned Cases", "AssignedCases", null, new { @class = "nav-link ml-0" })
        @Html.ActionLink("Processing", "AssignedCases", new { assigned = "Assigned" }, new { @class = "nav-link" })
        @Html.ActionLink("Not Processing", "AssignedCases", new { assigned = "Unassigned" }, new { @class = "nav-link" })
    }

</nav>
<hr class="mt-2 mb-4" />

<div class="card mb-4">
    <div class="card-header">@ViewBag.Title</div>
    <div class="card-body">
        <div class="datatable">
            @if (!Cases.Any())
            {
                <div class="py-4 text-center">
                    <h2 class="text-primary-soft">No cases</h2>
                    <p class="text-muted font-italic">There are no @(ViewBag.Title != null ? ViewBag.Title.ToLower() : "case ") yet</p>
                </div>
            }
            else
            {
                <table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Case ID</th>
                        <th>Subject</th>
                        <th>Client email</th>
                        <th>Status</th>
                        <th>Reported at</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var caseModel in Cases)
                    {
                        <tr>
                            <td>@caseModel.CaseID</td>
                            <td>@caseModel.ReportSubject</td>
                            <td>@caseModel.Email</td>
                            <td>
                                <div class="badge badge-@caseModel.GetBadgeColor() badge-pill">@caseModel.StatusID</div>
                            </td>
                            <td>@caseModel.SubmitDate</td>
                            <td class="d-flex">
                                <a class="btn btn-secondary btn-sm" href="@Url.Action("CaseDetails", new{ id = caseModel.Id })"><i data-feather="eye" class="mr-2"></i> View</a>
                            </td>
                        </tr>
                    }

                    </tbody>
                </table>
            }
            <div class="row">

                <div class="col-sm-12 col-md-5">
                    <div class="dataTables_info" id="dataTable_info" role="status" aria-live="polite">Showing  @PageInfo.CurrentPage out of @PageInfo.TotalPages</div></div>
                <div class="col-sm-12 col-md-6">
                    <div class="d-flex w-100">
                        <div class="btn-group ml-auto">
                            @if (User.IsInRole("Attorney General"))
                            {
                                @Html.PageLinks(Model.PageInfo, x => Url.Action("Index", new {page = x}))
                            }

                            @if (User.IsInRole("Director of Department"))
                            {
                                @Html.PageLinks(Model.PageInfo, x => Url.Action("DepartmentCases", new {page = x}))
                            }

                            @if (User.IsInRole("Lawyer"))
                            {
                                @Html.PageLinks(Model.PageInfo, x => Url.Action("AssignLawyer", new {page = x}))
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<!--<div class="dataTables_paginate paging_simple_numbers" id="dataTable_paginate">
<ul class="pagination">-->
@*<li class="paginate_button page-item previous" id="dataTable_previous"><a href="#" aria-controls="dataTable" data-dt-idx="0" tabindex="0" class="page-link">Previous</a></li><li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="1" tabindex="0" class="page-link">1</a></li><li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="2" tabindex="0" class="page-link">2</a></li><li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="3" tabindex="0" class="page-link">3</a></li><li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="4" tabindex="0" class="page-link">4</a></li><li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="5" tabindex="0" class="page-link">5</a></li><li class="paginate_button page-item active"><a href="#" aria-controls="dataTable" data-dt-idx="6" tabindex="0" class="page-link">6</a></li><li class="paginate_button page-item next disabled" id="dataTable_next"><a href="#" aria-controls="dataTable" data-dt-idx="7" tabindex="0" class="page-link">Next</a></li>*@
<!--</ul>
</div>-->

ministryofJusticeApp/ministryofjusticeWebUi/Views/Case/_SearchCase.cshtml
@using ministryofjusticeWebUi.Models
@model SearchCasesViewModel

<div class="page-header-search mt-4">
    @using (Html.BeginForm("SearchResult", "Case", FormMethod.Post, new { @id = "searchForm" }))
    {
        @Html.AntiForgeryToken();
        <div class="form-group">
            @Html.EnumDropDownListFor(m => m.Category,
                new { @class = "custom-select w-25 bg-gradient-light", @id = "inputGroupSelect01" })
        </div>
        <div class="input-group input-group-joined d-flex">
            @Html.TextBoxFor(m => m.SearchValue,
                new { @class = "form-control", placeholder = "Find case...", arialabel = "Search", autofocus = true })
            <div class="input-group-append">
                <button class="input-group-text"><i data-feather="search"></i></button>
            </div>
        </div>
    }
</div>