ministryofJusticeApp/ministryofjusticeWebUi/Models/DepartmentViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using ministryofjusticeDomain.Entities;

namespace ministryofjusticeWebUi.Models
{
    public class DepartmentViewModel
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Department name")]
        public string DepartmentName { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }
    }
}

ministryofJusticeApp/ministryofjusticeWebUi/Models/ManageDepartmentViewModel.cs
using System.Collections.Generic;
using ministryofjusticeDomain.Entities;
using ministryofjusticeDomain.IdentityEntities;

namespace ministryofjusticeWebUi.Models
{
    public class ManageDepartmentViewModel
    {
        public IEnumerable<Department> Departments { get; set; }
        public IEnumerable<ApplicationUser> Users { get; set; }
    }
}

ministryofJusticeApp/ministryofjusticeWebUi/Controllers/DepartmentController.cs
using System.Web.Mvc;
using AutoMapper;
using ministryofjusticeDomain.Entities;
using ministryofjusticeDomain.Interfaces;
using ministryofjusticeDomain.Interfaces.Repository;
using ministryofjusticeWebUi.Interfaces;
using ministryofjusticeWebUi.Models;

namespace ministryofjusticeWebUi.Controllers
{
	[Authorize]

	public class DepartmentController : Controller
	{
		private readonly IDepartmentServices _departmentServices;

		public DepartmentController()
		{
		}

		public DepartmentController(IDepartmentServices departmentServices) => _departmentServices = departmentServices;


		// GET: Department
		public ActionResult ManageDepartments()
		{
			var vm = _departmentServices.ManageDepartment();
			return View(vm);
		}

		[HttpGet]
		public ActionResult CreateDepartment()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult CreateDepartment(DepartmentViewModel model)
		{
			if (ModelState.IsValid)
			{
				var result = _departmentServices.CreateDepartment(model);
				if (result)
				{
					TempData["Message"] = "Department Created Successfully";
					return View("CreateDepartment");
				}
				ModelState.AddModelError("", "An Error Occured");
			}

			return View(model);
		}

		[HttpGet]
		public ActionResult UpdateDepartment(int id)
		{
			var department = _departmentServices.GetDepartmentById(id);
			return View(department);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult UpdateDepartment(DepartmentViewModel model)
		{
			var result = _departmentServices.UpdateDepartment(model);
			if (result)
			{
				TempData["Message"] = "Department Updated Successfully";
				return View("UpdateDepartment");
			}
			else
			{
				return HttpNotFound("There is no department found");

			}
		}
	}
}

ministryofJusticeApp/ministryofjusticeWebUi/Views/Department/CreateDepartment.cshtml
@model ministryofjusticeWebUi.Models.DepartmentViewModel
@{
    Layout = "_DepartmentLayout.cshtml";
    ViewBag.Title = "Create department";
}

<div class="card mb-4 col-md-8">
    <div class="card-header">Add a New Department</div>
    <div class="card-body">
        @using (Html.BeginForm("CreateDepartment", "Department", null, FormMethod.Post, new {@class = "form-horizontal", role = "form"}))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new {@class = "text-danger small"})
            <!--Email-->
            <div class="form-group">
                @Html.LabelFor(m => m.DepartmentName,
                    new {@class = "col-md-6 control-label"})
                <div>
                    @Html.TextBoxFor(m => m.DepartmentName,
                        new
                        {
                            @class = "form-control form-control-user",
                            @id = "exampleInputEmail",
                            @placeholder = "Enter first name"
                        })
                    @Html.ValidationMessageFor(m => m.DepartmentName, "", new {@class = "text-danger small"})
                </div>

            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Description,
                    new {@class = "col-md-6 control-label"})
                <div>
                    @Html.TextAreaFor(m => m.Description,
                        new
                        {
                            @class = "form-control form-control-user ",
                            @id = "exampleInputEmail",
                            @placeholder = " Information pertaining to the department"
                        })
                    @Html.ValidationMessageFor(m => m.Description, "", new {@class = "text-danger small"})
                </div>
            </div>
            <button type="submit" class="btn btn-primary btn-user btn-block">
                Create Department
            </button>
        }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ministryofJusticeApp/ministryofjusticeWebUi/Views/Department/ManageDepartments.cshtml
@using ministryofjusticeWebUi.Models
@model ManageDepartmentViewModel
@{
    Layout = "~/Views/Department/_DepartmentLayout.cshtml";
    ViewBag.Title = "Manage departments";
}

<div class="card mb-4">
    <div class="card-header d-flex justify-content-between">
        All Departments
        <a class="btn btn-sm btn-outline-primary" href="@Url.Action("CreateDepartment")"><i class="fa fa-plus mr-1"></i>Add Department</a>
    </div>
    <div class="card-body">
        @if (!Model.Departments.Any())
        {
            <p>There was no departments</p>
        }
        else
        {
            foreach (var department in Model.Departments)
            {
                <!-- Item 1-->
                <div class="d-flex align-items-center justify-content-between mb-4">
                    <div class="d-flex align-items-center flex-shrink-0 mr-3">
                        <div class="avatar avatar-xl mr-3 bg-gray-200">
                            <i data-feather="briefcase"></i>
                        </div>
                        <div class="d-flex flex-column font-weight-bold">
                            <a class="text-dark line-height-normal mb-1" href="#!">@Html.ActionLink(@department.DepartmentName, "UpdateDepartment", "Department", new { id = department.Id }, null)</a>
                            <div class="small text-muted line-height-normal">@( department.Lawyers != null ? $"{department.Lawyers.Count()} lawyers" : "No lawyer") <i data-feather="users"></i></div>
                        </div>
                    </div>
                    <div class="dropdown no-caret">
                        <button class="btn btn-transparent-dark btn-icon dropdown-toggle" id="dropdownPeople1" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i data-feather="more-vertical"></i>
                        </button>
                        <div class="dropdown-menu dropdown-menu-right animated--fade-in-up" aria-labelledby="dropdownPeople1">
                            <a class="dropdown-item text-secondary" href="#"><i data-feather="user-plus" class="mr-2"></i>Add members</a>
                            <a class="dropdown-item text-primary" href="#!"><i data-feather="edit-2" class="mr-2"></i>Edit department</a>
                            <a class="dropdown-item text-danger" href="#!"><i data-feather="trash" class="mr-2"></i>Delete department</a>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</div>

ministryofJusticeApp/ministryofjusticeWebUi/Views/Department/UpdateDepartment.cshtml
@model ministryofjusticeDomain.Entities.Department

@{
    Layout = "_DepartmentLayout.cshtml";
    ViewBag.Title = "UpdateDepartment";
}

<h2>UpdateDepartment</h2>


@using (Html.BeginForm("UpdateDepartment", "Department", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Department</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartmentName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepartmentName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ManageDepartments")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ministryofJusticeApp/ministryofjusticeWebUi/Views/Department/_DepartmentLayout.cshtml
@{
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
    <div class="container-fluid">
        <div class="page-header-content">
            <div class="row align-items-center justify-content-between pt-3">
                <div class="col-auto mb-3">
                    <h1 class="page-header-title">
                        <div class="page-header-icon">
                            <i data-feather="user"></i>
                        </div>
                        Departments - @ViewBag.Title
                    </h1>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container mt-4">
    <!-- Account page navigation-->
    <nav class="nav nav-borders">
        @Html.ActionLink("Manage Departments", "ManageDepartments", "Department", null, new {@class = "nav-link ml-0"})
        @Html.ActionLink("Add Department", "CreateDepartment", "Department", null, new {@class = "nav-link"})
    </nav>
    <hr class="mt-0 mb-4"/>
    @RenderBody()
</div>

@RenderSection("scripts", required: false)